// export default function Head() {
//   return (
//     <>
//       <title>About Page</title>
//       <meta content="width=device-width, initial-scale=1" name="viewport" />
//       <meta name="description" content="Generated by Vanessa" />
//       <link rel="icon" href="/favicon.ico" />
//     </>
//   );
// }

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Vanessa",
  description: "...",
};

export default function Page() {}
